### ISSUE TITLE
Demo project doesn't work

### ISSUE THREAD

**Issue by Tridus** [tomasjurasek/asp-net-core-multilingual-routing#1]
Hi. I tried this today, but simply downloading and running the demo project, translation doesn't work. URLs are not picking up the route translations and the links don't show up correctly. It looks like the translation transformer is never actually firing.

I tried implementing it on my own and had the same issue.

**Comment by tomasjurasek** [comment]
Hi, 
I’m refactoring this functionality. Please wait a few days for the update.

**Comment by tomasjurasek** [comment]
@Tridus visit the new repository - https://github.com/tomasjurasek/AspNetCore.Mvc.Routing.Localization, there is a new refactored package with the sample project.

**Comment by Tridus** [comment]
Thanks! The new one appears to work really well. :)
